FROM node:22-alpine

WORKDIR /app

# Copia package.json e package-lock.json
COPY package*.json ./

# Instala dependências
RUN npm install

# Copia todo o código
COPY . .

# Build da aplicação
RUN npm run build

RUN npm install -g serve

EXPOSE 3000


# Roda o app em produção usando npm start
CMD ["sh", "-c", "serve -s dist -l $PORT"]

