FROM node:22-alpine

WORKDIR /app

# Copia package.json e package-lock.json
COPY package*.json ./

# Instala dependências
RUN npm install

# Copia todo o código
COPY . .

# Build da aplicação
RUN npm run build



# Roda o app em produção usando npm start
CMD ["npm", "start"]
