FROM node:22-alpine

WORKDIR /app

# Copia package.json e package-lock.json
COPY package*.json ./

# Instala dependências
RUN npm install

# Copia todo o código
COPY . .


# Roda o app em produção usando npm start
CMD ["npm", "rum" ,"dev"]

