services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=mysql
      - DB_PORT=mysql
      - DB_USERNAME=bazar_user
      - DB_PASSWORD=bazarroot
      - DB_DATABASE=db_bazar
      - QUEUE_CONNECTION=redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CLIENT=predis

    volumes:
      - ./server:/var/www/html
      - /var/www/html/vendor

    depends_on:
      - mysql
      - redis
    networks:
      - laravel

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - laravel

  queue:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: php artisan queue:work --sleep=3 --tries=3 --timeout=90
    environment:
      - QUEUE_CONNECTION=redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CLIENT=predis
    depends_on:
      - mysql
      - redis
    restart: always
    networks:
      - laravel

  redis:
    image: redis:latest
    container_name: redis_ecommerce
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: ecommerce
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce

    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./server:/var/www/html
      - ./server/vendor:/var/www/html/vendor
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - server
    networks:
      - laravel


networks:
  laravel:
    driver: bridge

volumes:
  mysql_data:
  redis_data: